### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrdebo762** [gwen001/github-endpoints#5]
![deeb@eldeeb_ ~ 1_8_2023 8_02_06 PM](https://user-images.githubusercontent.com/70272354/211211642-ef0645eb-0fa2-43b8-8023-4ab53cb0532f.png)

**Comment by gwen001** [comment]
Hum yes, stupid mistake from me. You didn't provide any GitHub token so it cannot work properly. Check the help to know how to provide token. Thanks.
